name: Build and Publish Helm Chart

on:
  pull_request:
    branches:
    - "main"
  push:
    branches:
      - "*"
    tags:
      - '*'
  workflow_dispatch:

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout code
      #  uses: actions/checkout@v2
      #- name: Set up Helm
      #  uses: azure/setup-helm@v4.2.0
      #- name: Set up YQ
      #  uses: dcarbone/install-yq-action@v1
    - name: Kubernetes KinD Cluster
      uses: gotha/kind-action@v1.12.1-rc14
      with:
        registry: true
        registry_name: my-registry
        registry_port: 5001
        registry_enable_delete: true
    - name: test
      run: |
        which kubectl
        which kind
